carts/urls.py
from django.urls import path
from .views import cart_home,cart_update,checkout_home,cart_remove,cart_remove_wishlist,cart_remove_checkout

app_name = 'carts'


urlpatterns = [
    path('',cart_home,name= 'cart_home'),
     path('checkout',checkout_home,name= 'checkout'),
    path('update',cart_update,name= 'cart_update'),
    path('remove',cart_remove,name= 'cart_remove_product'),
    path('remove_wishlist',cart_remove_wishlist,name= 'cart_remove_product_wishlist'),
    path('remove_checkout',cart_remove_checkout,name= 'cart_remove_checkout'),
    
    
]

fishsell/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from addresses.views import checkout_address_create_view,deliver_time


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('checkout/address/create',checkout_address_create_view, name='checkout_address_create_view'),
    path('checkout/delivery_address/create/',deliver_time, name='checkout_address_create_delivery_address'),
    path('search/',include('search.urls', namespace='search')),
     path('carts/',include('carts.urls', namespace='cart')),
      path('payment/',include('mpesa.urls', namespace='mpesa')),
     path('account/' ,include('accounts.urls' , namespace = 'account')),
     path('contacts/' ,include('contacts.urls' , namespace = 'contacts'))
]

if settings.DEBUG:
    urlpatterns  =  urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns  =  urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mpesa/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (Index,
lipa_na_mpesa_online,
register_urls,
confirmation,
validation,
call_back,
cash_on_delivery,
cash_on_delivery_success,
simulate_mpesa
)

app_name = 'mpesa'


urlpatterns = [
    path('',Index,name='mpesaindex'),
    path('online/lipa', lipa_na_mpesa_online, name='lipa_na_mpesa'),

     # register, confirmation, validation and callback urls
    path('c2b/register', register_urls, name="register_mpesa_validation"),
    path('c2b/confirmation', confirmation, name="confirmation"),
    path('c2b/validation', validation, name="validation"),
    path('c2b/callback', call_back, name="call_back"),
    path('cash_on_delivery',cash_on_delivery, name="cash_on_delivery"),
    path('cash_on_delivery/success',cash_on_delivery_success, name="cash_on_delivery_success"),

    #simulate mpesa
    path('c2b/mpesa', simulate_mpesa, name="simulate_mpesa"),
    
    
]

mpesa/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# M-pesa Payment models

class MpesaCalls(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()

    class Meta:
        verbose_name = 'Mpesa Call'
        verbose_name_plural = 'Mpesa Calls'


class MpesaCallBacks(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()

    class Meta:
        verbose_name = 'Mpesa Call Back'
        verbose_name_plural = 'Mpesa Call Backs'


class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    type = models.TextField()
    reference = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()
    organization_balance = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'

    def __str__(self):
        return self.first_name

mpesa/forms.py
from django import forms

class CashAtHand(forms.Form):
    cash_at_hand = forms.IntegerField(widget=forms.NumberInput(
        attrs={  "type": "number"  , "placeholder" : "Enter the Cash At Hand In Order To get Change" , "class" : "form-control lgn_input" 
        
        }
    ))
    

mpesa/views.py
from django.shortcuts import render,redirect
from carts.models import Cart
from billing.models import BillingProfile
from addresses.models import Address,DeliveryTime
from orders.models import Order
from products.models import Category,Banners
from .forms import CashAtHand

#Email imports
from django.core.mail import send_mail,EmailMultiAlternatives
from django.template.loader import get_template
from django.conf import settings

#####################
# Create your views here.
from django.http import HttpResponse, JsonResponse
import requests
from requests.auth import HTTPBasicAuth
import json
from . mpesa_credentials import MpesaAccessToken, LipanaMpesaPpassword
from django.views.decorators.csrf import csrf_exempt
from .models import MpesaPayment

def Index(request):
    order_id = request.session.get('object' ,  None)
    cart_id = request.session.get('cart' , None)
    cart_items = request.session.get('cart_items' , None)
    allcategory = Category.objects.all()
    
    order_obj = Order.objects.get(order_id__iexact =order_id)
    cart_obj = Cart.objects.get(id__iexact = cart_id)
    context = {
        "object": order_obj,
        "cart_items" :  cart_items,
        "cart_obj" : cart_obj,
        "cart" : cart_obj,
        "delivery_method" : "continue with Mpesa"
       
    }
    return render(request, "mpesa.html", context)


def lipa_na_mpesa_online(request):
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = {
        "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
        "Password": LipanaMpesaPpassword.decode_password,
        "Timestamp": LipanaMpesaPpassword.lipa_time,
        "TransactionType": "CustomerPayBillOnline",
        "Amount": 1,
        "PartyA": 254704157038,  # replace with your phone number to get stk push
        "PartyB": LipanaMpesaPpassword.Business_short_code,
        "PhoneNumber": 254704157038,  # replace with your phone number to get stk push
        "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
        "AccountReference": "Lyrics Dribbler",
        "TransactionDesc": "Testing stk push"
    }
    response = requests.post(api_url, json=request, headers=headers)
    mpesa_respone = json.loads(response.text)
    return HttpResponse(mpesa_respone)




@csrf_exempt
def register_urls(request):
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
    headers = {"Authorization": "Bearer %s" % access_token}
    options = {"ShortCode": LipanaMpesaPpassword.Test_c2b_shortcode,
               "ResponseType": "Cancelled",
               "ConfirmationURL": "http://sleepy-savannah-28536.herokuapp.com/api/v1/c2b/confirmation",
               "ValidationURL": "http://sleepy-savannah-28536.herokuapp.com/api/v1/c2b/validation"}
    response = requests.post(api_url, json=options, headers=headers)

    return HttpResponse(response.text)


@csrf_exempt
def call_back(request):
    pass


@csrf_exempt
def validation(request):

    context = {
        "ResultCode": 0,
        "Amount" :  2,
        "ResultDesc": "Accepted"
    }
    return JsonResponse(dict(context))


@csrf_exempt
def confirmation(request):
    mpesa_body =request.body.decode('utf-8')
    mpesa_payment = json.loads(mpesa_body)
    payment = MpesaPayment(
        first_name=mpesa_payment['FirstName'],
        last_name=mpesa_payment['LastName'],
        middle_name=mpesa_payment['MiddleName'],
        description=mpesa_payment['TransID'],
        phone_number=mpesa_payment['MSISDN'],
        amount=mpesa_payment['TransAmount'],
        reference=mpesa_payment['BillRefNumber'],
        organization_balance=mpesa_payment['OrgAccountBalance'],
        type=mpesa_payment['TransactionType'],

    )
    payment.save()

    context = {
        "ResultCode": 0,
        "ResultDesc": "Accepted"
    }

    return JsonResponse(dict(context))



def cash_on_delivery(request):
    order_id = request.session.get('object' ,  None)
    cart_id = request.session.get('cart' , None)
    cart_items = request.session.get('cart_items' , None)
    address_id = request.session.get("delivery_address_id")
    all_address_with_specific_id = Address.objects.get(id = address_id)
    allcategory = Category.objects.all()
    order_obj = Order.objects.get(order_id__iexact =order_id)
    cart_obj = Cart.objects.get(id__iexact = cart_id)
    delivery_time_id  = request.session.get('delivery_time' , None)
    order_time = DeliveryTime.objects.get(id=delivery_time_id )
    cash_at_hand = CashAtHand()

    if  request.method == "POST" :
        if cash_at_hand.is_valid:
            cash_at_ = request.POST.get("cash_at_hand")
            order_obj.cash_at_hand = cash_at_ 
            expected_change_order = float(cash_at_) - float(order_obj.total)
            order_obj.change_expected = expected_change_order
            #to do: do some check to see that the order is done
            #update order object to being paid 
            # href="{% url 'mpesa:lipa_na_mpesa' %}"
            is_done = order_obj.check_done()
            if is_done:
                order_obj.mark_cash_on_delivery()
                del request.session['cart_id'] 
                return redirect("mpesa:cash_on_delivery_success")
        else:
            #to do: do some check to see that the order is done
            #update order object to being paid 
            # href="{% url 'mpesa:lipa_na_mpesa' %}"
            is_done = order_obj.check_done()
            if is_done:
                order_obj.mark_cash_on_delivery()
                del request.session['cart_id'] 
                return redirect("mpesa:cash_on_delivery_success")
            

    context = {
        "object": order_obj,
        "cart_items" :  cart_items,
        "cart_obj" : cart_obj,
        "cart" : cart_obj,
        "delivery_method" : "continue with cash on delivery",
        "form_cash" : "cash",
        "delivery_time" : order_time,
        "cash_at_hand"  : cash_at_hand

    }
    return render(request, "cash.html", context)


def cash_on_delivery_success(request):
    delivery_time_id  = request.session.get('delivery_time' , None)
    
    order_id = request.session.get('object' ,  None)
    cart_id = request.session.get('cart' , None)
    cart_items = request.session.get('cart_items' , None)
    allcategory = Category.objects.all()
    order_obj = Order.objects.get(order_id__iexact =order_id)
    cart_obj = Cart.objects.get(id__iexact = cart_id)
    order_time = DeliveryTime.objects.get(id=delivery_time_id )
    context = {
        "object": order_obj,
        "cart_items" :  cart_items,
        "cart_obj" : cart_obj,
        "cart" : cart_obj,
        "delivery_method" : "Cash On Delivery",
        'delivery_time_id' : order_time
    }
    
    #orders
    order_id_email = order_obj.order_id
    total_amount = order_obj.total
    order_arrival_date = order_time.date 
    
    subject = "Delivery for {}".format(order_id_email)
    from_email = settings.EMAIL_HOST_USER
    to_email = str(order_obj.delivery_address.email)
    message = "Your order was placed successfully Oder Id : f'{order_id_email}' Order Email : f'{to_email}'  Payment Method : Cash On delivery , Payment Amount : f'{total_amount}' Order Arrival Date :  f'{order_arrival_date}'  "
    emailsent = EmailMultiAlternatives(subject=subject, body=message ,from_email=from_email ,  to = [to_email] )
    html_template = get_template("success.html").render(context,request)
    emailsent.attach_alternative(html_template, "text/html")
    emailsent.send()


    
  
    
    return render(request, "success.html", context)


def simulate_mpesa(request):
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = { "ShortCode":LipanaMpesaPpassword.Test_c2b_shortcode,
        "CommandID":"CustomerPayBillOnline",
        "Amount":1,
        "Msisdn":254704157038,
        "BillRefNumber":" "
          }
  
    response = requests.post(api_url, json = request, headers=headers)
    return HttpResponse(response.text)

mpesa/templates/cash.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">		
		<title>Twala Fish </title>
		
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'images\fav.png' %}">
		
		<!-- Stylesheets -->
		<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
		<link href='vendor\unicons-2.0.1\css\unicons.css' rel='stylesheet'>
		<link href="{% static 'css\style.css' %}" rel="stylesheet">
		<link href="{% static 'css\responsive.css' %}" rel="stylesheet">
		<link href="{% static 'css\night-mode.css' %}" rel="stylesheet">
		<link href="{% static 'css\step-wizard.css' %}" rel="stylesheet">
		
		<!-- Vendor Stylesheets -->
		<link href="{% static 'vendor\fontawesome-free\css\all.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\bootstrap\css\bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'vendor\semantic\semantic.min.css' %}">	
		
	</head>

<body>
	<!-- Header Start -->
	<header class="header clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="top-header-group">
						<div class="top-header">
							<div class="res_main_logo">
								<a href="/"><img src="{% static 'images\dark-drawing.svg' %}" alt=""></a>
							</div>
							<div class="main_logo ml-0" id="logo">
								<a href="/"><img src="{% static 'images\drawing.svg' %}" alt=""></a>
								<a href="/"><img class="logo-inverse" src="{% static 'images\dark-drawing.svg' %}" alt=""></a>
							</div>
							<div class="header_right">
								<a href="#" class="report-btn hover-btn">Thank You</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->
	<!-- Body Start -->
	<div class="bill-dt-bg">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="bill-detail">
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Items</h4>
							</div>
							<div class="bill-descp">
                                <div class="itm-ttl">{{cart_items}} items</div>
                                {% if cart.products %}
                                {% for p in cart.products.all %}
                                <span class="item-prdct">{{p.product_title }} 1kg</span>
                                {% endfor %}
                                {% endif %}
							
							</div>
                        </div>
                        <div class="bill-dt-step">
							<div class="bill-title">
								<h4>Delivery Address</h4>
							</div>
							<div class="bill-descp">
								<div class="itm-ttl"></div>
								<p class="bill-address">{{object.delivery_address.name}},{{object.delivery_address.phone}},{{object.delivery_address.email}}</p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Order Details</h4>
							</div>
							<div class="bill-descp">
								
								<p class="bill-dt-sl">Order ID - <span class="descp-bll-dt">{{object.order_id}}</span></p>
								<p class="bill-dt-sl">Items - <span class="descp-bll-dt">{{cart_items}}</span></p>
								<p class="bill-dt-sl">Timing - <span class="descp-bll-dt">{{delivery_time.date}}</span></p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment</h4>
							</div>
							<div class="bill-descp">
								<div class="total-checkout-group p-0 border-top-0">
									<div class="cart-total-dil">
										<h4>Subtotal</h4>
										<span>Ksh : {{object.cart.total }}</span>
									</div>
									<div class="cart-total-dil pt-3">
										<h4>Delivery Charges</h4>
										<span>Ksh : {{object.shipping_total }}</span>
									</div>
								</div>
								<div class="main-total-cart pl-0 pr-0 pb-0 border-bottom-0">
									<h2>Total</h2>
									<span>Ksh : {{object.total }}</span>
								</div>
							</div>
						</div>
						
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment Option</h4>
							</div>
							<div class="bill-descp">
								<p class="bill-dt-sl"><span class="dlr-ttl25 mr-1"><i class="uil uil-check-circle"></i></span>Cash on Delivery</p>
							</div>
						</div>
						<form method="POST">
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Enter Cash At Hand*</h4>
							</div>
							<div class="bill-descp">
								{{cash_at_hand.cash_at_hand}}
							</div>
						</div>
						<div class="bill-dt-step">
							
							{% comment %} <div class="bill-title">
								<h4>Enter Cash At Hand*</h4>
							</div>
							<div class="bill-descp">
								{{cash_at_hand.cash_at_hand}}
							</div> {% endcomment %}
							

							<div class="bill-bottom">
								<div class="thnk-ordr">Thanks for Ordering</div>
								
								
									{% csrf_token %}
								
								<button class="print-btn hover-btn" type="submit" >{{delivery_method}}</button>
							</form>
							</div>
					
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Body End -->
	
	<!-- Javascripts -->
	<script src="{ static 'js\jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor\bootstrap\js\bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor\OwlCarousel\owl.carousel.js' %}"></script>
	<script src="{% static 'vendor\semantic\semantic.min.js' %}"></script>
	<script src="{% static 'js\jquery.countdown.min.js' %}"></script>
	<script src="{% static 'js\custom.js' %}"></script>
	<script src="{% static 'js\product.thumbnail.slider.js' %}"></script>
	<script src="{% static 'js\offset_overlay.js' %}"></script>
	<script src="{% static 'js\night-mode.js' %}"></script>
	
	
</body>
</html>

mpesa/templates/mpesa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">		
		<title>Twala Fish </title>
		
		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'images\fav.png' %}">
		
		<!-- Stylesheets -->
		<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
		<link href='vendor\unicons-2.0.1\css\unicons.css' rel='stylesheet'>
		<link href="{% static 'css\style.css' %}" rel="stylesheet">
		<link href="{% static 'css\responsive.css' %}" rel="stylesheet">
		<link href="{% static 'css\night-mode.css' %}" rel="stylesheet">
		<link href="{% static 'css\step-wizard.css' %}" rel="stylesheet">
		
		<!-- Vendor Stylesheets -->
		<link href="{% static 'vendor\fontawesome-free\css\all.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\OwlCarousel\assets\owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor\bootstrap\css\bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'vendor\semantic\semantic.min.css' %}">	
		
	</head>

<body>
	<!-- Header Start -->
	<header class="header clearfix">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="top-header-group">
						<div class="top-header">
							<div class="res_main_logo">
								<a href="/"><img src="{% static 'images\dark-drawing.svg' %}" alt=""></a>
							</div>
							<div class="main_logo ml-0" id="logo">
								<a href="/"><img src="{% static 'images\drawing.svg' %}" alt=""></a>
								<a href="/"><img class="logo-inverse" src="{% static 'images\dark-drawing.svg' %}" alt=""></a>
							</div>
							<div class="header_right">
								<a href="#" class="report-btn hover-btn">Thank You</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->
	<!-- Body Start -->
	<div class="bill-dt-bg">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8">
					<div class="bill-detail">
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Items</h4>
							</div>
							<div class="bill-descp">
                                <div class="itm-ttl">{{cart_items}} items</div>
                                {% if cart.products %}
                                {% for p in cart.products.all %}
                                <span class="item-prdct">{{p.product_title }} 1kg</span>
                                {% endfor %}
                                {% endif %}
							
							</div>
                        </div>
                        <div class="bill-dt-step">
							<div class="bill-title">
								<h4>Delivery Address</h4>
							</div>
							<div class="bill-descp">
								<div class="itm-ttl"></div>
								<p class="bill-address">{{object.delivery_address.name}},{{object.delivery_address.phone}},{{object.delivery_address.billing_profile}}</p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Order Details</h4>
							</div>
							<div class="bill-descp">
								
								<p class="bill-dt-sl">Order ID - <span class="descp-bll-dt">{{object.order_id}}</span></p>
								<p class="bill-dt-sl">Items - <span class="descp-bll-dt">{{cart_items}}</span></p>
								<p class="bill-dt-sl">Timing - <span class="descp-bll-dt">26 May 2020 , Tuesday, 3.00PM - 5.00PM</span></p>
							</div>
						</div>
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment</h4>
							</div>
							<div class="bill-descp">
								<div class="total-checkout-group p-0 border-top-0">
									<div class="cart-total-dil">
										<h4>Subtotal</h4>
										<span>Ksh : {{object.cart.total }}</span>
									</div>
									<div class="cart-total-dil pt-3">
										<h4>Delivery Charges</h4>
										<span>Ksh : {{object.shipping_total }}</span>
									</div>
								</div>
								<div class="main-total-cart pl-0 pr-0 pb-0 border-bottom-0">
									<h2>Total</h2>
									<span>Ksh : {{object.total }}</span>
								</div>
							</div>
						</div>
						
						<div class="bill-dt-step">
							<div class="bill-title">
								<h4>Payment Option</h4>
							</div>
							<div class="bill-descp">
								<p class="bill-dt-sl"><span class="dlr-ttl25 mr-1"><i class="uil uil-check-circle"></i></span>Mpesa</p>
							</div>
						</div>
						<div class="bill-dt-step">
							<form method="POST" action="{% url 'mpesa:register_mpesa_validation' %}">
							<div class="bill-bottom">
								<div class="thnk-ordr">Thanks for Ordering</div>
								
								
									{% csrf_token %}
									
								<button class="print-btn hover-btn" type="submit" >{{delivery_method}}</button>
							</form>
							</div>
					
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Body End -->
	
	<!-- Javascripts -->
	<script src="{ static 'js\jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor\bootstrap\js\bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor\OwlCarousel\owl.carousel.js' %}"></script>
	<script src="{% static 'vendor\semantic\semantic.min.js' %}"></script>
	<script src="{% static 'js\jquery.countdown.min.js' %}"></script>
	<script src="{% static 'js\custom.js' %}"></script>
	<script src="{% static 'js\product.thumbnail.slider.js' %}"></script>
	<script src="{% static 'js\offset_overlay.js' %}"></script>
	<script src="{% static 'js\night-mode.js' %}"></script>
	
	
</body>
</html>