accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import signin,signup,guest_register_view

app_name = 'accounts'


urlpatterns = [
    path('',signin,name= 'signin'),
     path('signup',signup,name= 'signup'),
     path('signup/guest/',guest_register_view,name= 'guest_register'),
     path('logout',LogoutView.as_view() , name="logout"),
    
    
]

carts/urls.py
from django.urls import path
from .views import cart_home,cart_update,checkout_home,cart_remove,cart_remove_wishlist,cart_remove_checkout

app_name = 'carts'


urlpatterns = [
    path('',cart_home,name= 'cart_home'),
     path('checkout',checkout_home,name= 'checkout'),
    path('update',cart_update,name= 'cart_update'),
    path('remove',cart_remove,name= 'cart_remove_product'),
    path('remove_wishlist',cart_remove_wishlist,name= 'cart_remove_product_wishlist'),
    path('remove_checkout',cart_remove_checkout,name= 'cart_remove_checkout'),
    
    
]

contacts/urls.py
from django.urls import path
from .views import index

app_name = 'contacts'


urlpatterns = [
    path('',index,name= 'contacts_index'),
     
    
    
]

fishsell/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from addresses.views import checkout_address_create_view,deliver_time


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('checkout/address/create',checkout_address_create_view, name='checkout_address_create_view'),
    path('checkout/delivery_address/create/',deliver_time, name='checkout_address_create_delivery_address'),
    path('search/',include('search.urls', namespace='search')),
     path('carts/',include('carts.urls', namespace='cart')),
      path('payment/',include('mpesa.urls', namespace='mpesa')),
     path('account/' ,include('accounts.urls' , namespace = 'account')),
     path('contacts/' ,include('contacts.urls' , namespace = 'contacts'))
]

if settings.DEBUG:
    urlpatterns  =  urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns  =  urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (ItemDetailView,
FeaturedProducts,
NewProduct,
Index,
ItemDetailViewCategory)

app_name = 'products'


urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('category/<slug>/', ItemDetailViewCategory.as_view(), name='category'),
    path('newproducts/', NewProduct.as_view(), name='newproducts'),
    path('featuredproducts/', FeaturedProducts.as_view(), name='featured'),
    
]

search/urls.py
from django.conf.urls import url

from .views import (
        SearchProductView
        )

app_name = 'search'
urlpatterns = [
    url('', SearchProductView.as_view(), name='query'),
]

products/models.py
from django.db import models
import random
import os
from django.db.models import Q
from datetime import datetime
from django.utils.timezone import now
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from fishsell.utils import unique_slug_generator,category_unique_slug_generator
# Create your models here.



def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )

def upload_image_path2(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "categories/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    category_image = models.FileField(upload_to = upload_image_path2 ,null=True,blank=False)
    category_description = models.TextField()
    slug = models.SlugField(blank=True,unique=True)
    

    def __str__(self):
        return self.category_name
    
    def get_absolute_url(self):
        return reverse("products:category", kwargs={
            'slug': self.slug
        })

class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(Active=True)
    def featured(self):
        return self.filter(featured_product=True)
    def search(self, query):
        lookups = (Q(product_title__icontains=query) | 
                  Q(product_full_description__icontains=query) |
                  Q(product_price__icontains=query) 
                  )
        # tshirt, t-shirt, t shirt, red, green, blue,
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):

    def all(self):
        return self.get_queryset().active()
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)
    def featured(self): #Product.objects.featured() 
        return self.get_queryset().featured()
    def search(self, query):
        return self.get_queryset().active().search(query)
    

class Products(models.Model):
    product_title = models.CharField(max_length=100)
    product_overview = models.CharField(max_length=100)
    product_full_description = models.TextField()
    product_category = models.ForeignKey(Category,on_delete=models.CASCADE)
    product_quantity_in_kgs = models.DecimalField(max_digits=5, decimal_places=2)
    product_price = models.DecimalField(max_digits=5, decimal_places=2)
    product_discount_price = models.DecimalField(max_digits=5, decimal_places=2,blank=True,null=True)
    Active = models.BooleanField(default=True)
    product_Image_Field = models.ImageField(upload_to=upload_image_path,null=True,blank=False)
    featured_product = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=now, editable=False)
    slug = models.SlugField(blank=True,unique=True)
    objects = ProductManager()
    def __str__(self):
        return self.product_title
    
    def get_percentage_off(self):
        newmoriginal = self.product_price - self.product_discount_price
        percentage = (newmoriginal/self.product_price) * 100
        return int(percentage)
    def new_products(self):
        original_date = self.created_date
        subtracteddate = original_date - now()

        return subtracteddate
    
    def return_two_weeks(self):
        two_weeks = datetime.timedelta(hours=336)
        return two_weeks
    def get_absolute_url(self):
        return reverse("products:product", kwargs={
            'slug': self.slug
        })

    def moreq(self):
        qs = MoreProductQuantirty.objects.all()
        return qs
  
    



def product_presave_reciver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_presave_reciver,sender = Products)

def category_presave_reciver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = category_unique_slug_generator(instance)


pre_save.connect(category_presave_reciver,sender = Category)

# class PostImage(models.Model):
#     product = models.ForeignKey(Products, default=None, on_delete=models.CASCADE)
#     more_images = models.ImageField(upload_to=upload_image_path,null=True,blank=True)

#     def __str__(self):
#         return self.product.product_title

# class MoreProductQuantirty(models.Model):
#     product_more = models.ForeignKey(Products, default=None, on_delete=models.CASCADE)
#     more_product_quantity = models.DecimalField(max_digits=5, decimal_places=2,blank=True,null=True)

#     def __str__(self):
#         return self.product_more.product_title


class Banners(models.Model):
    product_Image_Field = models.ImageField(upload_to=upload_image_path,null=True,blank=False)

        





    

search/models.py
from django.db import models

# Create your models here.

products/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Products,Banners
from django.views.generic import DetailView,View,ListView
from carts.models import Cart



class Index(View):
    def get(self,request,*args,**kwargs):
        allproducts = Products.objects.all()
        allcategory = Category.objects.all()
        cart_obj,new_obj = Cart.objects.new_or_get(self.request)
        cart_items  = cart_obj.products.count()
        allbanners = Banners.objects.all()
        context = {
            'categories' : allcategory,
            'products' : allproducts,
            'cart' : cart_obj,
            'cart_items' :  cart_items,
            'allbanners' : allbanners
        }
    
        return render(request,'homepage/index.html',context)









class ItemDetailView(DetailView):
    model = Products
    template_name = "homepage/product_single_view.html"
    def get_context_data(self, **kwargs):
        featuredpd = Products.objects.all()
        allcategory = Category.objects.all()
        cart_obj,new_obj = Cart.objects.new_or_get(self.request)
        cart_items  = cart_obj.products.count()
        context = super().get_context_data(**kwargs)
        context['featuredpd'] = featuredpd
        context['cart'] = cart_obj
        context['categories'] = allcategory
        context['cart_items'] = cart_items
        
        
        return context

class ItemDetailViewCategory(DetailView):
    model = Category
    template_name = "categoryproducts/category.html"
    def get_context_data(self, **kwargs):
        allproducts = Products.objects.all()
        allcategory = Category.objects.all()
        cart_obj,new_obj = Cart.objects.new_or_get(self.request)
        cart_items  = cart_obj.products.count()
        context = super().get_context_data(**kwargs)
        context['fproducts'] = allproducts
        context['cart'] = cart_obj
        context['categories'] = allcategory
        context['cart_items'] = cart_items
        
         
        return context
    




class NewProduct(ListView):
    model = Products
    template_name = 'newproducts/newproducts.html'
    context_object_name = 'newproducts'
    paginate_by = 12
    def get_context_data(self, **kwargs):
        allcategory = Category.objects.all()
        cart_obj,new_obj = Cart.objects.new_or_get(self.request)
        cart_items  = cart_obj.products.count()
        context = super().get_context_data(**kwargs)
        context['cart'] = cart_obj
        context['categories'] = allcategory
        context['cart_items'] = cart_items
        return context



class FeaturedProducts(ListView):
    template_name = 'featuredproducts/featured.html'
    context_object_name = 'fproducts'
    paginate_by = 12

    def get_queryset(self,*args,**kwargs):
        request = self.request
        return Products.objects.all().featured()
    def get_context_data(self, **kwargs):
        allcategory = Category.objects.all()
        cart_obj,new_obj = Cart.objects.new_or_get(self.request)
        cart_items  = cart_obj.products.count()
        context = super().get_context_data(**kwargs)
        context['cart'] = cart_obj
        context['categories'] = allcategory
        context['cart_items'] = cart_items
        return context

search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Products

class SearchProductView(ListView):
    template_name = "search/view.html"
    context_object_name = 'fproducts'
    paginate_by = 12

  
    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None) # method_dict['q']
        if query is not None:
            return Products.objects.search(query)
        
        return Products.objects.all().featured()

products/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% include "head.html" %}
    {% block extrahead %}
    {% endblock %}

    <body>
        
        {% block icons %}

        {% endblock %}
        {% block featured %}
        {% endblock %}
        {% include "categorystart.html" %}
        {% include "searchmodelstart.html" %}
        {% include "cart_offset_sidebar.html" %}
        {% include "headerstart.html" %}
        {% block content %}

        {% endblock %}

        {% include "footer.html" %}
        {% include "jsfiles.html" %}
        {% block extrajs %}
        {% endblock %}

    </body>








</html>

products/templates/cart_offset_sidebar.html
{% load static %}

<!-- Cart Sidebar Offset Start-->
<div class="bs-canvas bs-canvas-left position-fixed bg-cart h-100">
    <div class="bs-canvas-header side-cart-header p-3 ">
        <div class="d-inline-block  main-cart-title">My Cart <span>({{ cart_items }} Items)</span></div>
        <button type="button" class="bs-canvas-close close" aria-label="Close"><i class="uil uil-multiply"></i></button>
    </div> 
    <div class="bs-canvas-body">
        <div class="cart-top-total">
            
        </div>
        <div class="side-cart-items">
            {% if cart.products %}
            {% for p in cart.products.all %}
            
            <div class="cart-item">
                <div class="cart-product-img">
                    <img height="100" width="100" src="{{p.product_Image_Field.url}}" alt="">
                    {% if p.product_discount_price %}
                    <div class="offer-badge">{{p.get_percentage_off}}% OFF</div>
                    {% endif %}
                </div>
                <div class="cart-text">
                    <h4>{{p.product_title }}</h4>
                 
                    <div class="qty-group">
                       
                        {% if p.product_discount_price %}
                            <div class="product-price">Ksh : {{p.product_discount_price}} <span> ksh : {{p.product_price}}</span></div>
                        {% else %}
                            <div class="product-price">Ksh : {{p.product_price}} </div>
                        {% endif %}
                    </div>
                    
                <form method ='POST' action = '{% url "carts:cart_update" %}' class="form">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{p.id}}"/>
                
                    <button type="submit" class="cart-close-btn"><i class="uil uil-trash-alt"></i></button>
                </form>
                
                </div>
            </div>
            {% endfor %}
          
            {% else %}
            <h1>Your cart is Empty</h1>
            {% endif %}
            
        </div>
    </div>
    <div class="bs-canvas-footer">
        <div class="main-total-cart">
            <h2>Sub Total</h2>
            <span>Ksh : {{cart.subtotal}}</span>
        </div>
        {% if cart.products %}
        <div class="checkout-cart">
            <a href="#" class="promo-code">Thank You </a>
            <a href='{% url "carts:checkout" %}' class="cart-checkout-btn hover-btn">Proceed to Checkout</a>
        </div>
        {% endif %}
    </div>
</div>
<!-- Cart Sidebar Offsetl End-->

products/templates/categorystart.html
    {% load static %}
    
    <!-- Category Model Start-->
	<div id="category_model" class="header-cate-model main-gambo-model modal fade" tabindex="-1" role="dialog" aria-modal="false">
        <div class="modal-dialog category-area" role="document">
            <div class="category-area-inner">
                <div class="modal-header">
                    <button type="button" class="close btn-close" data-dismiss="modal" aria-label="Close">
						<i class="uil uil-multiply"></i>
                    </button>
                </div>
                <div class="category-model-content modal-content"> 
					<div class="cate-header">
						<h4>Select Category</h4>
					</div>
                    <ul class="category-by-cat">
						
						{% if categories %}
						{% for c in categories %}
						<li>
							<a href='{{c.get_absolute_url}}'  class="single-cat-item">
								<div class="icon">
									<img height="100" width="100"src="{{c.category_image.url}}" alt="">
								</div>
								<div class="text"> {{c.category_name}}</div>
							</a>
						</li>
						{% endfor %}
						{% endif %}
                    </ul>
					<a href="#" class="morecate-btn"><i class="uil uil-apps"></i>More Categories</a>
                </div>
            </div>
        </div>
    </div>
	<!-- Category Model End-->

products/templates/footer.html
{% load static %}

<footer class="footer">
    <div class="footer-first-row">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <ul class="call-email-alt">
                        <li><a href="#" class="callemail"><i class="uil uil-dialpad-alt"></i>254-700-057005</a></li>
                        <li><a href="#" class="callemail"><i class="uil uil-envelope-alt"></i>info@twalafishstore.com</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="social-links-footer">
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                        </ul>
                    </div>
                </div>				
            </div>
        </div>
    </div>
    <div class="footer-second-row">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    {% if categories %}
                    
                    <div class="second-row-item">
                        <h4>Categories</h4>
                        <ul>
                            {% for c in categories %}
                            <li><a href="{{c.get_absolute_url}}">{{c.category_name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    
                    {% endif %}
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><a href="about_us.html">About</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'cart:checkout' %}">Checkout</a></li>
                            <li><a href="{% url "accounts:logout" %}">Log Out</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
                            
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

                            {% endif %}

                            <li><a href="{% url 'contacts:contacts_index' %}">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item-app">
                        <h4>Download App</h4>
                        <ul>
                            <li><a href="#"><img class="download-btn" src="{% static 'images\download-1.svg' %}" alt=""></a></li>
                            <li><a href="#"><img class="download-btn" src="{% static 'images\download-2.svg' %}" alt=""></a></li>
                        </ul>
                    </div>
                    <div class="second-row-item-payment">
                        <h4>Payment Method</h4>
                        <div class="footer-payments">
                            <ul id="paypal-gateway" class="financial-institutes">
                                <li class="financial-institutes__logo">
                                  <img alt="Mpesa" title="Mpesa" src="{% static 'images\footer-icons\mpesa_image.jpeg' %}">
                                </li>
                             
                               
                            
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="footer-last-row">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-bottom-links">
                        <ul>
                            <li><a href="about_us.html">About</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'cart:checkout' %}">Checkout</a></li>
                            <li><a href="{% url "accounts:logout" %}">Log Out</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:signin' %}">Sign In</a></li>
                            
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

                            {% endif %}

                            <li><a href="{% url 'contacts:contacts_index' %}">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="copyright-text">
                        <i class="uil uil-copyright"></i>Copyright 2020 <b>Gambolthemes</b> . All rights reserved
                    </div>



                </div>
            </div>
        </div>
    </div>
</footer>

products/templates/form.html
<form method="POST" action='{% if action_url %}{{ action_url }}{% else %}{% url "login" %}{% endif %}'>
    {% csrf_token %}
    {% if address_type %}
    <input type="hidden" name="address_type" value="{{address_type}}" />
    {% endif %}
    {{form}}
  
  <button type="submit" class="btn btn-primary" > Submit </button>
  </form>

products/templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=9">
    <meta name="description" content="Gambolthemes">
    <meta name="author" content="Gambolthemes">		
    <title>Twala Fish</title>
    
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="{% static 'images\fav.png' %}">
    
    <!-- Stylesheets -->
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href='{% static "vendor\unicons-2.0.1\css\unicons.css" %}' rel='stylesheet'>
    <link href="{% static 'css\style.css' %}" rel="stylesheet">
    <link href="{% static 'css\responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css\night-mode.css' %}" rel="stylesheet">
    
    <!-- Vendor Stylesheets -->
    <link href="{% static 'vendor\fontawesome-free\css\all.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor\OwlCarousel\assets\owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'vendor\OwlCarousel\assets\owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor\bootstrap\css\bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor\semantic\semantic.min.css' %}">	
    
</head>

products/templates/headerstart.html
{% load static %}
<!-- Header Start -->
<header class="header clearfix">
    <div class="top-header-group">
        <div class="top-header">
            <div class="res_main_logo">
                <!-- <a href="/"><img src="{% static 'images\dark-logo-1.svg' %}" alt=""></a> -->
            </div>
            <div class="main_logo" id="logo">
                
                <a href="/"><img src="{% static 'images\drawing.svg' %}" alt=""></a>
                <a href="/"><img class="logo-inverse" src="{% static 'images\dark-drawing.svg' %}" alt=""></a>
           
            </div>
          
            {% include 'search-form.html' %}
          
            <div class="header_right">
                <ul>
                    <li>
                        <a href="#" class="offer-link"><i class="uil uil-phone-alt"></i>254-700-057005</a>
                    </li>
                  
                   
                    {% if request.user.is_authenticated %}
                    
                    <li>
                        <a href='{% url "carts:cart_home" %}' class="option_links" title="Wishlist"><i class='uil uil-heart icon_wishlist'></i><span class="noti_count1">{{ cart_items }}</span></a>
                    </li>
                    	
                    <li class="ui dropdown">
                        <a href="#" class="opts_account">
                            <img src="{% static 'images\avatar\img-5.jpg' %}" alt="">
                            <span class="user__name">{{request.user.username}}</span>
                            <i class="uil uil-angle-down"></i>
                        </a>
                        <div class="menu dropdown_account">
                            <div class="night_mode_switch__btn">
                                <a href="#" id="night-mode" class="btn-night-mode">
                                    <i class="uil uil-moon"></i> Night mode
                                    <span class="btn-night-mode-switch">
                                        <span class="uk-switch-button"></span>
                                    </span>
                                </a>
                            </div>	
                            							
                        
                            <a href='{% url "carts:cart_home" %}' class="item channel_item"><i class="uil uil-heart icon__1"></i>My Wishlist</a>
                        
                            
                            <a href='{% url "accounts:logout" %}' class="item channel_item"><i class="uil uil-lock-alt icon__1"></i>Logout</a>
                        </div>
                    </li>

                    {% else %}
                    <li>
                        <a href='{% url "accounts:signin" %}'><span class="hidden-xs">Log In</span></a>
                    </li>
                    <li>
                        <a href='{% url "accounts:signup" %}'><span class="hidden-xs">Sign Up</span></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="sub-header-group">
        <div class="sub-header">
            <div class="ui dropdown">
                <a href="#" class="category_drop hover-btn" data-toggle="modal" data-target="#category_model" title="Categories"><i class="uil uil-apps"></i><span class="cate__icon">Select Category</span></a>
            </div>
            <nav class="navbar navbar-expand-lg navbar-light py-3">
                <div class="container-fluid">
                    <button class="navbar-toggler menu_toggle_btn" type="button" data-target="#navbarSupportedContent"><i class="uil uil-bars"></i></button>
                    <div class="collapse navbar-collapse d-flex flex-column flex-lg-row flex-xl-row justify-content-lg-end bg-dark1 p-3 p-lg-0 mt1-5 mt-lg-0 mobileMenu" id="navbarSupportedContent">
                        <ul class="navbar-nav main_nav align-self-stretch">
                            <li class="nav-item"><a href="/" class="nav-link active" title="Home">Home</a></li>
                            <li class="nav-item"><a href="{% url 'products:newproducts' %}" class="nav-link new_item" title="New Products">New Products</a></li>
                            <li class="nav-item"><a href="{% url 'products:featured' %}" class="nav-link" title="Featured Products">Featured Products</a></li>
                            <li class="nav-item">
                                <div class="ui icon top left dropdown nav__menu">
                                    <a class="nav-link" title="Pages">Pages <i class="uil uil-angle-down"></i></a>
                                    <div class="menu dropdown_page">
                                     
                                        <a href="about_us.html" class="item channel_item page__links">About Us</a>
                                        {% if request.user.is_authenticated %}
                                        <a href="{% url 'cart:checkout' %}" class="item channel_item page__links">Checkout</a>
                                      
                                        
                                         <a href="{% url "accounts:logout" %}" class="item channel_item page__links">Logout</a>	
                                        {% else %}
                                        <a href="{% url 'accounts:signin' %}" class="item channel_item page__links">Sign In</a>
                                        <a href="{% url 'accounts:signup' %}" class="item channel_item page__links">Sign Up</a>
                                        {% endif %}
                                      									
                                        <a href="{% url 'contacts:contacts_index' %}" class="item channel_item page__links">Contact Us</a>
                                    </div>
                                </div>
                            </li>
                     
                            <li class="nav-item"><a href="{% url 'contacts:contacts_index' %}" class="nav-link" title="Contact">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="catey__icon">
                <a href="#" class="cate__btn" data-toggle="modal" data-target="#category_model" title="Categories"><i class="uil uil-apps"></i></a>
            </div>
            <div class="header_cart order-1">
                <a href="#" class="cart__btn hover-btn pull-bs-canvas-left" title="Cart"><i class="uil uil-shopping-cart-alt"></i><span>Cart</span><ins>{{ cart_items }}</ins><i class="uil uil-angle-down"></i></a>
            </div>
         
    </div>
</header>
<!-- Header End -->

products/templates/search-form.html
<form method='GET' action='{% url "search:query" %}' class="form my-2 my-lg-0 search-form">
    <div class='input-group'>
      <input class="form-control" type="text" placeholder="Search" name='q' aria-label="Search" value='{{ request.GET.q }}'>
      <span class='input-group-btn'>
          <button class="btn btn-outline-success" type="submit">Search</button>
      </span>
      </div>
  </form>
  